### PR TITLE
Pin and update node version

### PR DESCRIPTION
**Pull request by danielcooperxyz**
Update and pin node version

### CODE REVIEW

**Review by mattdean-digicatapult — CHANGES_REQUESTED** [review]
Two things to do:

* bump the service version
* update github workflows to use `16.x` instead of `14.x`

**Review by n3op2 — APPROVED** [review]
go single quotes!

**Review by mattdean-digicatapult — APPROVED** [review]

**Review by darrylmorton-digicatapult — APPROVED** [review]

**Review by dblane-digicatapult — APPROVED** [review]

**Review by darrylmorton-digicatapult — CHANGES_REQUESTED** [review]
Dockerfile npm version

**Comment by mattdean-digicatapult** [comment]
@darrylmorton-digicatapult 

> Dockerfile npm version

Is changed to `8.x.x`. What are you expecting?

**Review by darrylmorton-digicatapult — APPROVED** [review]

**Comment by darrylmorton-digicatapult** [comment]
> @darrylmorton-digicatapult
> 
> > Dockerfile npm version
> 
> Is changed to `8.x.x`. What are you expecting?

My bad, couldn't see the change.

**Comment by danielcooperxyz** [comment]
> go single quotes!

Thanks for pointing that out. I think that was my editor/extensions. I should probably change those back, if we have a pre-existing convention.

**Pull request merged**
